[project]
name = "robot-orchestra-2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-blinka>=8.47.0",
    "adafruit-circuitpython-trellis>=1.3.19",
    "numpy>=2.1.1",
    "rpi-lgpio>=0.6",
]
